### ISSUE TITLE
panic when submitting an event

### ISSUE THREAD

**Issue by millken** [machinefi/w3bstream#273]
request 
```
echo '{"events":[{"header":{"event_id":"'$EVENTID'","event_type":"'$EVENTTYPE'","pub_id":"'$PUBKEY'","pub_time":'`date +%s`',"token":"'$PUBTOKEN'"},"payload":"xxx yyy zzz"}]}' | http post :8888/srv-applet-mgr/v0/event/$PROJECTNAME

http: LogLevel.ERROR: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing a POST request to URL: http://localhost:8888/srv-applet-mgr/v0/event/word_count
```
w3bstream log
```
2022/12/28 19:03:45 http: panic serving 127.0.0.1:55884: runtime error: invalid memory address or nil pointer dereference
goroutine 494 [running]:
net/http.(*conn).serve.func1()
        /Users/millken/.gvm/gos/go1.18.6/src/net/http/server.go:1825 +0xb0
panic({0x102338840, 0x102959810})
        /Users/millken/.gvm/gos/go1.18.6/src/runtime/panic.go:844 +0x258
github.com/machinefi/w3bstream/pkg/modules/event.OnEventReceived({0x102434170?, 0x1400127bf80}, {0x140012b7cde, 0xa}, 0x1400045c300)
        /Users/millken/work/iotexproject/w3bstream/pkg/modules/event/event.go:65 +0x314
github.com/machinefi/w3bstream/pkg/modules/event.HandleEvents({0x102434170, 0x1400127bf80}, {0x140012b7cde, 0xa}, 0x140012c5ea0)
        /Users/millken/work/iotexproject/w3bstream/pkg/modules/event/event.go:109 +0xf4
github.com/machinefi/w3bstream/cmd/srv-applet-mgr/apis/event.(*HandleEvent).Output(0x140012c5e90, {0x102434170?, 0x140012c5ec0})
        /Users/millken/work/iotexproject/w3bstream/cmd/srv-applet-mgr/apis/event/pos.go:27 +0x160
github.com/machinefi/w3bstream/pkg/depends/kit/httptransport.(*RouteHandler).ServeHTTP(0x140003bf1a0, {0x102431b50, 0x140020fb950}, 0x1400045c200)
        /Users/millken/work/iotexproject/w3bstream/pkg/depends/kit/httptransport/route_handler.go:86 +0x6d4
net/http.HandlerFunc.ServeHTTP(0x102434170?, {0x102431b50?, 0x140020fb950?}, 0x1029a67f8?)
        /Users/millken/.gvm/gos/go1.18.6/src/net/http/server.go:2084 +0x3c
github.com/julienschmidt/httprouter.(*Router).Handler.func1({0x102431b50?, 0x140020fb950?}, 0x1400045c100?, {0x140012d4700?, 0x140012c5ce0?, 0x30?})
        /Users/millken/.gvm/pkgsets/go1.18.6/global/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:275 +0x2a8
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x140005dd860, {0x102431b50, 0x140020fb950}, 0x1400045c100)
        /Users/millken/.gvm/pkgsets/go1.18.6/global/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x744
github.com/machinefi/w3bstream/pkg/depends/kit/httptransport.(*HttpTransport).ServeHTTP(0x140012e32c8?, {0x102431b50?, 0x140020fb950?}, 0x1023f0fe0?)
        /Users/millken/work/iotexproject/w3bstream/pkg/depends/kit/httptransport/transport.go:74 +0x2c
github.com/machinefi/w3bstream/pkg/depends/conf/http/mws.(*pprofHandler).ServeHTTP(0x140004ba5e8?, {0x102431b50?, 0x140020fb950?}, 0x1400045c100?)
        /Users/millken/work/iotexproject/w3bstream/pkg/depends/conf/http/mws/pprof.go:43 +0x1cc
github.com/machinefi/w3bstream/pkg/depends/conf/http.NewContextInjectorMw.func1.1({0x102431b50?, 0x140020fb950?}, 0x1400045c000?)
        /Users/millken/work/iotexproject/w3bstream/pkg/depends/conf/http/context.go:17 +0x274
net/http.HandlerFunc.ServeHTTP(0x1024339c8?, {0x102431b50?, 0x140020fb950?}, 0x140012e3500?)
```

**Comment by saitofun** [comment]
fixed pr #270
